### ISSUE TITLE
terrain error

### ISSUE THREAD

**Issue by Crab-Tang** [CesiumGS/cesium-native#274] opened 2021-07-02 07:17 UTC
![image](https://user-images.githubusercontent.com/63999331/124231707-3bf2ed00-db43-11eb-8dbf-a69558c26dd9.png)
#

when i load a terrain( not the cesium ion) it has some tile err.

**Comment by Crab-Tang** [comment] 2021-07-02 07:18
![@4UYBWTN)I~F`0(Y E@XEWO](https://user-images.githubusercontent.com/63999331/124236208-c25dfd80-db48-11eb-80df-c19681142eae.png)

**Comment by baothientran** [comment] 2021-07-02 20:28
hi @Crab-Tang if you don't mind, can you please share the asset to us for debugging purpose? If it can't be shared with the public, you can send it to support@cesium.com

**Comment by Crab-Tang** [comment] 2021-07-05 06:06
I sent it to your email, please check it

**Comment by Crab-Tang** [comment] 2021-07-05 06:06
> hi @Crab-Tang if you don't mind, can you please share the asset with us for debugging purpose? If it can't be shared with the public, you can send it to [support@cesium.com](mailto:support@cesium.com)

I sent the data to your email, please check it

**Comment by Crab-Tang** [comment] 2021-07-09 09:00
> hi @Crab-Tang if you don't mind, can you please share the asset with us for debugging purpose? If it can't be shared with the public, you can send it to [support@cesium.com](mailto:support@cesium.com)

hi @baothientran Did you find any clues

**Comment by Crab-Tang** [comment] 2021-07-11 13:16
> hi @Crab-Tang if you don't mind, can you please share the asset with us for debugging purpose? If it can't be shared with the public, you can send it to [support@cesium.com](mailto:support@cesium.com)

hi， did you have some clue , Maybe there is something wrong with the up sampling？

**Comment by baothientran** [comment] 2021-07-11 23:56
Hi @Crab-Tang

This looks like the imagery doesn't map correctly to the upsampled tile, especially when the high level tile (level 15) is upsampled from very low tile (level 0). For example, this tile below only has two imagery tiles mapped to it. @kring do you have any hints of what may be the cause for this one? FYI the tile in the image below is upsampled from a tile level 0

![Capture](https://user-images.githubusercontent.com/20376598/125213709-6fd7bc00-e281-11eb-9ab1-733efe060dc6.PNG)

@Crab-Tang I took a look at the data, and it seems like the binary quantized mesh doesn’t contain the metadata for availability, which makes Cesium Unreal only display the very top level.

To provide you some context, in the past, the availability was embedded in the layer.json, which your asset is currently storing in the available field. However, it doesn’t work well with high resolution terrain dataset which covers a very large area because at the highest LOD, the quadtree can store more than thousand tiles, which may affect system’s memory. So we work around that by placing the availability within the tile binary content. That availability doesn’t cover the whole subtree to the leaf. Rather, we may only specify the availability for every next 5 (or smaller number if you want) level child tiles. For example, in the tile level 0, the availability will be specified up to tiles level 5. Then for every tile level 5, there will be availability up to tiles level 10, and so on.

CesiumJS provides backward combability with the availability in the layer.json, but it will be deprecated soon. Unfortunately, Cesium Unreal doesn’t provide that functionality. The workaround currently is to move the available field in the layer.json into the quantized mesh’s metadata extension. The format is the same as the available field in the layer.json. In other word, you can embed the below json into the binary quantized mesh:
```
{
    "available": [
        [
            {
                "endX": 1,
                "endY": 0,
                "startX": 0,
                "startY": 0
            }
        ],
        [
            {
                "endX": 3,
                "endY": 1,
                "startX": 2,
                "startY": 0
            }
        ]
    ]
}
```
This section from [quantized mesh specification](https://github.com/CesiumGS/quantized-mesh#metadata) has more information about storing metadata into the quantized mesh content.

I also link this [cesium-native code](https://github.com/CesiumGS/cesium-native/blob/1e784cabc515f78d3da245ac0677a9972da7f0f7/Cesium3DTiles/src/QuantizedMeshContent.cpp#L1176) that is used to parse the quantized mesh’s metadata in case it helps to adjust your asset

**Comment by Crab-Tang** [comment] 2021-07-12 01:18
![image](https://user-images.githubusercontent.com/63999331/125216119-bbc14a00-e2ef-11eb-9d37-e1d9fdd1c1b1.png)
I have Send the Second Email ,  That data contains "available“， and I Debuged ,   I found that.If I only give the data of layer 0, the sampling on the first layer is correct, and the second layer is wrong

**Comment by Crab-Tang** [comment] 2021-07-12 01:23
> Hi @Crab-Tang
> 
> This looks like the imagery doesn't map correctly to the upsampled tile, especially when the high level tile (level 15) is upsampled from very low tile (level 0). For example, this tile below only has two imagery tiles mapped to it. @kring do you have any hints of what may be the cause for this one? FYI the tile in the image below is upsampled from a tile level 0
> 
> ![Capture](https://user-images.githubusercontent.com/20376598/125213709-6fd7bc00-e281-11eb-9ab1-733efe060dc6.PNG)
> 
> @Crab-Tang I took a look at the data, and it seems like the binary quantized mesh doesn’t contain the metadata for availability, which makes Cesium Unreal only display the very top level.
> 
> To provide you some context, in the past, the availability was embedded in the layer.json, which your asset is currently storing in the available field. However, it doesn’t work well with high resolution terrain dataset which covers a very large area because at the highest LOD, the quadtree can store more than thousand tiles, which may affect system’s memory. So we work around that by placing the availability within the tile binary content. That availability doesn’t cover the whole subtree to the leaf. Rather, we may only specify the availability for every next 5 (or smaller number if you want) level child tiles. For example, in the tile level 0, the availability will be specified up to tiles level 5. Then for every tile level 5, there will be availability up to tiles level 10, and so on.
> 
> CesiumJS provides backward combability with the availability in the layer.json, but it will be deprecated soon. Unfortunately, Cesium Native doesn’t provide that functionality. The workaround currently is to move the available field in the layer.json into the quantized mesh’s metadata extension. The format is the same as the available field in the layer.json. In other word, you can embed the below json into the binary quantized mesh:
> 
> ```
> {
>     "available": [
>         [
>             {
>                 "endX": 1,
>                 "endY": 0,
>                 "startX": 0,
>                 "startY": 0
>             }
>         ],
>         [
>             {
>                 "endX": 3,
>                 "endY": 1,
>                 "startX": 2,
>                 "startY": 0
>             }
>         ]
>     ]
> }
> ```
> 
> This section from [quantized mesh specification](https://github.com/CesiumGS/quantized-mesh#metadata) has more information about storing metadata into the quantized mesh content.
> 
> I also link this [cesium-native code](https://github.com/CesiumGS/cesium-native/blob/1e784cabc515f78d3da245ac0677a9972da7f0f7/Cesium3DTiles/src/QuantizedMeshContent.cpp#L1176) that is used to parse the quantized mesh’s metadata in case it helps to adjust your asset


hi ,
![image](https://user-images.githubusercontent.com/63999331/125216999-4014cc80-e2f2-11eb-8573-76d798574805.png)

I have Send the Second Email , That data contains "available“， and  I found that.If I only give the data of level 0, the sampling on the one level is correct, and the second level is wrong

**Comment by baothientran** [comment] 2021-07-12 03:19
I can confirm that this happens even with Cesium CWT if I disable the metadata all together and only use the first levels

**Comment by kring** [comment] 2021-07-12 03:32
It could be a symptom of https://github.com/CesiumGS/cesium-native/issues/93. Level zero terrain tiles of course stretch all the way to the North and South poles. Which means that some of the texture coordinates are going to be dodgy. In the most extreme case, texture coordinates at the poles will be undefined, and so interpolating new texture coordinates at tile boundaries from those undefined values will not go well.

Or it could be a totally unrelated bug.

**Comment by baothientran** [comment] 2021-07-12 04:09
That's a good point! I definitely see some weird boundary of upsampled tiles, which indicates some problems with texture coordinates

**Comment by Crab-Tang** [comment] 2021-07-13 06:12
![image](https://user-images.githubusercontent.com/63999331/125399691-872eba80-e3e3-11eb-9986-ae34a0f161ad.png)
![image](https://user-images.githubusercontent.com/63999331/125399794-a75e7980-e3e3-11eb-87f0-63d0d7879457.png)
![image](https://user-images.githubusercontent.com/63999331/125399840-b513ff00-e3e3-11eb-8ef3-1552a052a8f0.png)
 @kring  It may not only be related to texture coordinates,  Tile mesh may also have errors

**Comment by kring** [comment] 2021-07-13 06:19
When your imagery resolution exceeds your terrain resolution, as is definitely the case here, we create more detailed geometry tiles by subdividing the coarse ones. This involves interpolating vertex positions, and that interpolation is done using texture coordinates. So yes, bad texture coordinates can lead to bad geometry.

**Comment by kring** [comment] 2021-08-05 01:33
This is caused by a combination of CesiumGS/cesium-native#292 and CesiumGS/cesium-native#93. Closing as a duplicate.

**Closed by kring** 2021-08-05 01:33 UTC
