### ISSUE TITLE
Unable to save Meshoptimizer compressed models as uncompressed glb models

### ISSUE THREAD

**Issue by xinghaoyujianni** [CesiumGS/cesium-native#785] opened 2024-01-04 03:36 UTC
I have the following code and the saved decompress.glb is not getting loaded！

GltfReader reader;
  GltfReaderResult result = reader.readGltf(readFile("C:\\Users\\EXT_meshopt_compression.glb"));
  Model& model = result.model.value();

  CesiumGltfWriter::GltfWriter writer;
  CesiumGltfWriter::GltfWriterOptions options;
  options.binaryChunkByteAlignment = 4; 

  const std::vector<std::byte> readModelBuffer = model.buffers[0].cesium.data;
  CesiumGltfWriter::GltfWriterResult writeResult =
      writer.writeGlb(model, gsl::span(readModelBuffer), options);
  const std::vector<std::byte>& glbBytesDefaultPadding = writeResult.gltfBytes;

  std::ofstream ofs("C:\\Users\\decompress.glb", std::ios::binary | std::ios::trunc | std::ios::out);
  ofs.write(
      (const char*)glbBytesDefaultPadding.data(),
      glbBytesDefaultPadding.size());
  ofs.flush();
  ofs.close();

**Comment by csciguy8** [comment] 2024-01-04 16:51
I think you're going to have to do a little debugging on your end here.

It's ok if you discover a bug in the cesium-native code, and want to share an example problem that reproduces it.

But in this case, it's not clear whether the problem is in cesium-native, or your test setup.

**Comment by j9liu** [comment] 2024-02-21 19:21
Hey @xinghaoyujianni,

Are you still experiencing this issue? If so, can you provide more details? In particular, it's not clear what you mean by the "glb is not getting loaded".

Otherwise, if this is no longer relevant, or if we don't receive a response, I'll close this issue.

**Closed** 2024-10-31 18:22 UTC
