### ISSUE TITLE
Cannot load quantized mesh from local file

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium-native#264] opened 2021-06-15 15:15 UTC
When trying to load a quantized mesh from a local file URL, it loads the `layer.json` properly. But when it comes to the `.terrain` files, the loader does not recognize them.

The reason is that at https://github.com/CesiumGS/cesium-native/blob/f9aba251e1bb7ec4ec66f7f1f00de9032b75c9ed/Cesium3DTiles/src/Tile.cpp#L286 , the response content type is (or may be) empty when the data is read from a file.

(As such, this might be considered as an issue of `cesium-unreal`, because this is the `UnrealAssetResponse` at this point...).

---

I'm not entirely sure about the best solution here. Is there a reasonable way to identify a `.terrain` file? (It does not appear to have a magic header. (Why?)). Quirky workarounds would involve passing the information along with the request. For network-based requests, this is "implicitly" done, via the Accept- and ContentType info. But it would be preferable to find a solution that solely affects https://github.com/CesiumGS/cesium-native/blob/f9aba251e1bb7ec4ec66f7f1f00de9032b75c9ed/Cesium3DTiles/src/TileContentFactory.cpp#L35 ...

**Comment by kring** [comment] 2021-06-16 01:15
This is a duplicate of #196.

**Closed** 2021-06-16 14:41 UTC
