### ISSUE TITLE
Export targets in Cmake configuration

### ISSUE THREAD

**Issue by jtorresfabra** [CesiumGS/cesium-native#247] opened 2021-05-14 13:31 UTC
Would be great if cesium-native export the targets in the cmake configuration so for an external application can be as easy as find_package(cesium-native) and then link against CesiumNative::CesiumNative or each individual library like CesiumNative::CesiumGeospatial. 

CC: https://github.com/CesiumGS/cesium-native/issues/231

**Comment by kring** [comment] 2022-05-09 04:43
Duplicate of #231.

**Closed by kring** 2022-05-09 04:43 UTC
